name: main

on:
  workflow_call:
    outputs:
      run-status:
        value: ${{ jobs.main.outputs.run-status }}

jobs:
  main:
    outputs:
      run-status: ${{ steps.build.outcome }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: echo "This is commit $SHA with another change" > ./sha.txt
        env:
          SHA: ${{ github.sha }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./sha.txt
