name: deploy

on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: my-artifact
          path: ./sha.txt
      - run: cat ./sha.txt
