name: deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "github.sha: ${{ github.sha }}"'
      - run: 'echo "github.event.inputs.name: ${{ github.event.inputs.name }}"'
      - run: 'echo "github.run_id: ${{ github.run_id }}"'
      - uses: actions/download-artifact@v2
        if: ${{ !github.event.inputs.name }}
        with:
          name: my-artifact
      - uses: dawidd6/action-download-artifact@v2
        if: ${{ github.event.inputs.name }}
        with:
          workflow: main.yml
          name: my-artifact
          commit: ${{ github.event.inputs.name }}
      - run: ls -la
      - run: cat ./sha.txt
