name: deploy

on: workflow_call

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "${{ github.run_id }}"

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: my-artifact
          run_id: ${{ github.run_id }}

      - name: List filesystem
        run: ls -la

      - name: Print file content
        run: cat ./sha.txt
