name: deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      sha:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.sha || github.sha }}"
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: my-artifact
          commit: ${{ inputs.sha || github.sha }}
      - run: cat ./sha.txt
