name: main

on:
  push:
    branches:
      - main

jobs:
  setup:
    outputs:
      last-run-status: ${{ steps.last-run-status.outputs.last-run-status }}
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Set default run status
        run: echo "::set-output name=last-run-status::default" > last-run-status

      - name: Restore last run status
        uses: actions/cache@v2
        with:
          path: |
            last-run-status
          key: ${{ github.run_id }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ github.run_id }}-

      - name: Set last run status
        id: last-run-status
        run: cat last-run-status

  build:
    needs: setup
    if: needs.setup.outputs.last-run-status != 'success'
    uses: thomasheyenbrock/rollback-testing/.github/workflows/build.yml@main

  deploy:
    needs: [setup, build]
    if: success() || cancelled()
    uses: thomasheyenbrock/rollback-testing/.github/workflows/deploy.yml@main
    with:
      use-historic-artifact: ${{ needs.setup.outputs.last-run-status == 'success' }}

  run-status:
    needs: [setup, deploy]
    if: needs.setup.outputs.last-run-status != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ needs.setup.outputs.last-run-status }}"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Restore last run status
        uses: actions/cache@v2
        with:
          path: |
            last-run-status
          key: ${{ github.run_id }}-${{ steps.date.outputs.date }}

      - name: Save run status
        run: echo "::set-output name=last-run-status::${{ needs.deploy.outputs.run-status }}" > last-run-status
