name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: thomasheyenbrock/rollback-testing/.github/workflows/build.yml@main
  deploy:
    needs: build
    uses: thomasheyenbrock/rollback-testing/.github/workflows/deploy.yml@main
